[package]
name = "lean-graph"
version = "0.1"
lean_version = "3.4.2"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "e66e1f30d8a0a006ff93a309cc202ab4deaebf04"}
